version: '3.8'

services:
  # Redis service for session management
  redis:
    image: redis:7-alpine
    container_name: visio-conf-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - visio-conf-network

  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visio-conf-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=5000
      - SESSION_SECRET=${SESSION_SECRET:-your-super-secret-session-key}
      
      # ZEGOCLOUD Configuration
      - ZEGOCLOUD_APP_ID=${ZEGOCLOUD_APP_ID}
      - ZEGOCLOUD_SERVER_SECRET=${ZEGOCLOUD_SERVER_SECRET}
      
      # France Travail OAuth Configuration
      - FRANCETRAVAIL_CLIENT_ID=${FRANCETRAVAIL_CLIENT_ID}
      - FRANCETRAVAIL_CLIENT_SECRET=${FRANCETRAVAIL_CLIENT_SECRET}
      - FRANCETRAVAIL_REDIRECT_URI=${FRANCETRAVAIL_REDIRECT_URI:-http://localhost:5000/api/auth/francetravail/callback}
      
      # Redis Configuration
      - REDIS_URL=redis://redis:6379
      
      # Monitoring (optional)
      - SENTRY_DSN=${SENTRY_DSN}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - visio-conf-network

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: visio-conf-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      app:
        condition: service_healthy
    networks:
      - visio-conf-network
    profiles:
      - production

volumes:
  redis_data:
    driver: local
  app_logs:
    driver: local
  nginx_logs:
    driver: local

networks:
  visio-conf-network:
    driver: bridge

